name: flutter_application_1a
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.12
  http: ^1.3.0
  toastification: ^3.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/diet.png
